### ISSUE TITLE
feature suggestion: writing status optional

### ISSUE THREAD

**Issue by Danii0206** [Talaren/FoundryVTT-PlayerStatus#35]
Hi,

I just found this module and really like how it handles the afk-status. But I already have another module for the writing status and I like their style a bit better. Nothing wrong with this one, just personal preference. Is it possible to implement an option to toggle the writing status on/off in this module, so I can use the afk-status only?

Kind regards
Danii

**Comment by Talaren** [comment]
@Danii0206 what addon do you use for writing status?
I add an option

**Comment by Danii0206** [comment]
Thank you very much! 
I use Cautious Gamemaster's Pack for writing status.

**Comment by Talaren** [comment]
The addon looks great, looks very cool.
