### ISSUE TITLE
Support of Chat Commands Lib

### ISSUE THREAD

**Issue by SesuUisu** [Talaren/FoundryVTT-PlayerStatus#41]
Please support the Lib: Chat Commands
https://github.com/League-of-Foundry-Developers/Chat-Commands-Lib

**Comment by Talaren** [comment]
@SesuUisu Unfortunately the addon is outdated, would hate to have a dependency on a V9 addon

**Comment by SesuUisu** [comment]
A new module dev has taken over https://gitlab.com/woodentavern/foundryvtt-chat-command-lib

**Comment by Talaren** [comment]
Ok thanks, I am working on an integration.
